spring:
  application:
    name: task-manager

task-manager:
  notificationExpiration: P30D

aws:
  dynamoDb:
    accessKeyId: ${DYNAMO_DB_ACCESS_KEY_ID:dummyaccesskeyid}
    secretKey: ${DYNAMO_DB_SECRET_KEY:dummysecretkey}
    url: ~
    alm:
      tableName: apphub-task_manager-${environment}-alm
    invitation:
      tableName: apphub-task_manager-${environment}-invitation
    notification:
      tableName: apphub-task_manager-${environment}-notification
    organization:
      tableName: apphub-task_manager-${environment}-organization