apiVersion: apps/v1
kind: Deployment
metadata:
  name: elite-base
  labels:
    app: elite-base
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elite-base
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: elite-base
    spec:
      containers:
      - name: elite-base
        image: saphyra/apphub-service-custom-elite_base:latest
        env:
        - name: SPRING_ACTIVE_PROFILE
          value: server,preprod
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        startupProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3600
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: elite-base
  labels:
    app: elite-base
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: elite-base