apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-gateway
  labels:
    app: main-gateway
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: main-gateway
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: main-gateway
    spec:
      containers:
      - name: main-gateway
        image: saphyra/apphub-service-platform-main_gateway:latest
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server,preprod
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        startupProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3600
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: main-gateway
  labels:
    app: main-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    name: main-gateway