apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storage
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: storage
    spec:
      containers:
      - name: storage
        image: saphyra/apphub-service-platform-storage:latest
        env:
        - name: FTP_CLIENT_USERNAME
          value: ftp_dev
        - name: SPRING_ACTIVE_PROFILE
          value: server,preprod
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        startupProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3600
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: storage