apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  labels:
    app: task-manager
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: task-manager
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: task-manager
    spec:
      containers:
        - name: task-manager
          image: saphyra/apphub-service-feature-task_manager:latest
          env:
            - name: SPRING_ACTIVE_PROFILE
              value: server,preprod
            - name: DYNAMO_DB_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dynamo-db-configuration
                  key: DYNAMO_DB_ACCESS_KEY_ID
            - name: DYNAMO_DB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dynamo-db-configuration
                  key: DYNAMO_DB_SECRET_KEY
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          startupProbe:
            httpGet:
              path: /platform/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 3600
          livenessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager
  labels:
    app: task-manager
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: task-manager