spring:
  application:
    name: admin-panel

liquibase:
  schema: admin_panel

role:
  settings:
    - pattern: /web/admin-panel
      methods:
        - GET
      requiredRoles:
        - ADMIN
    - pattern: /api/admin-panel/error-report
      methods:
        - POST
      requiredRoles:
        - ADMIN