spring:
  application:
    name: admin-panel
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

role:
  settings:
    - pattern: /web/admin-panel
      methods:
        - GET
      requiredRoles:
        - ADMIN