spring:
  application:
    name: main-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      server:
        webflux:
          predicate:
            weight:
              enabled: false
          globalcors:
            enabled: false
          routes:
            #FRONTEND
            - id: frontend
              uri: http://${serviceHosts.frontend}
              predicates:
                - "Path=\
                /,\
                /web,\
                /web/error,\
                /web/modules,\
                /web/skyxplore,\
                /web/skyxplore/character,\
                /web/skyxplore/lobby,\
                /web/skyxplore/game,\
                /web/skyxplore/game/admin,\
                /web/skyxplore/game/admin/**,\
                /web/notebook,\
                /web/notebook/**,\
                /web/admin-panel/migration-tasks,\
                /web/admin-panel/roles-for-all,\
                /web/admin-panel/role-management,\
                /web/admin-panel/disabled-role-management,\
                /web/admin-panel/error-report,\
                /web/admin-panel/error-report/*,\
                /web/admin-panel/ban,\
                /web/admin-panel/ban/*,\
                /web/admin-panel/performance-reporting,\
                /web/monitoring,\
                /web/utils/base64,\
                /web/utils/json-formatter,\
                /web/elite-base,\
                /web/elite-base/*,\
                /web/util/direction,\
                /web/calendar,\
                /web/calendar/**,\
                /web/user/account"
              filters:
                - StripPrefix=${stripPrefix.web}
            - id: frontend-resources
              uri: http://${serviceHosts.frontend}
              predicates:
                - Path=/web/static/**
              filters:
                - StripPrefix=${stripPrefix.static}
            #RESOURCES
            - id: common-resources
              uri: http://${serviceHosts.webContent}
              predicates:
                - Path=/res/common/**, /res/admin-panel/**, /res/community/**, /res/utils/**, /res/user/**
            - id: training-resources
              uri: http://${serviceHosts.training}
              predicates:
                - Path=/res/training/**

            #PAGES
            - id: common-pages
              uri: http://${serviceHosts.webContent}
              predicates:
                - Path=/web/community
            - id: training-pages
              uri: http://${serviceHosts.training}
              predicates:
                - Path=/web/training/**

            #MODULES
            - id: user
              uri: http://${serviceHosts.user}
              predicates:
                - Path=/api/user/**
            - id: authorization
              uri: http://${serviceHosts.authorization}
              predicates:
                - Path=/api/authorization/**
            - id: notebook
              uri: http://${serviceHosts.notebook}
              predicates:
                - Path=/api/notebook/**
            - id: admin-panel
              uri: http://${serviceHosts.adminPanel}
              predicates:
                - Path=/api/admin-panel/**
            - id: modules
              uri: http://${serviceHosts.modules}
              predicates:
                - Path=/api/modules/**
            - id: skyxplore-data
              uri: http://${serviceHosts.skyxploreData}
              predicates:
                - Path=/api/skyxplore/data/**
            - id: skyxplore-lobby
              uri: http://${serviceHosts.skyxploreLobby}
              predicates:
                - Path=/api/skyxplore/lobby/**
            - id: skyxplore-game
              uri: http://${serviceHosts.skyxploreGame}
              predicates:
                - Path=/api/skyxplore/game/**
            - id: training
              uri: http://${serviceHosts.training}
              predicates:
                - Path=/api/training/**
            - id: community
              uri: http://${serviceHosts.community}
              predicates:
                - Path=/api/community/**
            - id: calendar
              uri: http://${serviceHosts.calendar}
              predicates:
                - Path=/api/calendar/**
            - id: storage
              uri: http://${serviceHosts.storage}
              predicates:
                - Path=/api/storage/**
            - id: elite-base
              uri: http://${serviceHosts.eliteBase}
              predicates:
                - Path=/api/elite-base/**
            - id: monitoring
              uri: http://${serviceHosts.monitoring}
              predicates:
                - Path=/api/monitoring/**

            #WS
            - id: web-socket-admin-panel
              uri: ws://${serviceHosts.adminPanel}
              predicates:
                - Path=/api/ws/admin-panel/**
            - id: web-socket-skyxplore-lobby
              uri: ws://${serviceHosts.skyxploreLobby}
              predicates:
                - Path=/api/ws/skyxplore-lobby/**
            - id: web-socket-skyxplore-data
              uri: ws://${serviceHosts.skyxploreData}
              predicates:
                - Path=/api/ws/skyxplore-data/**
            - id: web-socket-skyxplore-game
              uri: ws://${serviceHosts.skyxploreGame}
              predicates:
                - Path=/api/ws/skyxplore-game/**

stripPrefix:
  web: 10
  static: 1

authorization:
  publicKey: ${PUBLIC_KEY}
  expirationDuration:
    accessToken: ${authorization.accessTokenExpiration}

delay:
  filter:
    enabled: false

role:
  settings:
    #Global
    - pattern: /web/**
      methods:
        - GET
      requiredRoles:
        - ACCESS
      whitelistedEndpoints:
        - pattern: /web/error
          method: GET
        - pattern: /web
          method: GET
    - pattern: /api/**
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      requiredRoles:
        - ACCESS
      whitelistedEndpoints:
        - pattern: /api/user/authentication/login
          method: POST
        - pattern: /api/user/authentication/logout
          method: POST
        - pattern: /api/user/authentication/session
          method: GET
        - pattern: /api/user
          method: POST
        - pattern: /api/user/ban/details
          method: POST
    #Training
    - pattern: /web/training/**
      methods:
        - GET
      requiredRoles:
        - TRAINING
    #Notebook
    - pattern: /web/notebook
      methods:
        - GET
      requiredRoles:
        - NOTEBOOK
    - pattern: /web/notebook/**
      methods:
        - GET
      requiredRoles:
        - NOTEBOOK
    - pattern: /api/notebook/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - NOTEBOOK
    #User
    - pattern: /api/user/data/roles
      methods:
        - POST
        - PUT
        - DELETE
      requiredRoles:
        - ADMIN
    - pattern: /api/user/data/roles/**
      methods:
        - PUT
        - DELETE
        - POST
      requiredRoles:
        - ADMIN
    - pattern: /api/user/data/roles/disabled
      methods:
        - GET
      requiredRoles:
        - ADMIN
    - pattern: /api/user/data/roles/all
      methods:
        - POST
        - DELETE
      requiredRoles:
        - ADMIN
    - pattern: /api/user/ban
      methods:
        - POST
        - GET
        - PUT
        - DELETE
      requiredRoles:
        - ADMIN
    - pattern: /api/user/ban/**
      methods:
        - POST
        - GET
        - PUT
        - DELETE
      requiredRoles:
        - ADMIN
    #Admin-panel
    - pattern: /web/admin-panel/**
      methods:
        - GET
        - POST
        - DELETE
        - PUT
      requiredRoles:
        - ADMIN
    - pattern: /api/admin-panel/**
      methods:
        - GET
        - POST
        - DELETE
        - PUT
      requiredRoles:
        - ADMIN
    #Monitoring
    - pattern: /api/monitoring/**
      methods:
        - GET
        - POST
        - DELETE
        - PUT
      requiredRoles:
        - ADMIN
    - pattern: /web/monitoring
      methods:
        - GET
      requiredRoles:
        - ADMIN
    #SkyXplore
    - pattern: /web/skyxplore/** #Generic SkyXplore pages
      methods:
        - GET
      requiredRoles:
        - SKYXPLORE
    - pattern: /web/skyxplore/game/admin #Landing page of SkyXplore admin pages
      methods:
        - GET
      requiredRoles:
        - ADMIN
    - pattern: /web/skyxplore/game/admin/** #SkyXplore admin pages
      methods:
        - GET
      requiredRoles:
        - ADMIN
    - pattern: /api/skyxplore/** #Generic SkyXplore endpoints
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE
    - pattern: /api/skyxplore/game/tick #Admin endpoint for manually processing a tick
      methods:
        - POST
      requiredRoles:
        - ADMIN
    - pattern: /api/skyxplore/game/admin/** #SkyXplore admin endpoints
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - ADMIN
    #Utils
    - pattern: /web/utils/**
      methods:
        - GET
      requiredRoles:
        - UTILS
    #Community
    - pattern: /web/community
      methods:
        - GET
      requiredRoles:
        - COMMUNITY
    - pattern: /api/community/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - COMMUNITY
    #Calendar
    - pattern: /web/calendar
      methods:
        - GET
      requiredRoles:
        - CALENDAR
    - pattern: /api/calendar/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - CALENDAR
    #EliteBase
    - pattern: /web/elite-base/**
      methods:
        - GET
      requiredRoles:
        - ELITE_BASE
    - pattern: /api/elite-base/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - ELITE_BASE
    - pattern: /api/elite-base/material-trader-override/*
      methods:
        - POST
        - DELETE
      requiredRoles:
        - ELITE_BASE_ADMIN