server:
  port: 8080

stripPrefix:
  web: 0
  static: 0

delay:
  filter:
    enabled: true
    paths:
      - path: /api/notebook/**
        enabled: false
        minDelay: PT3S
        maxDelay: PT5S
      - path: /api/**
        enabled: false
        minDelay: PT2S
        maxDelay: PT2S