spring:
  application:
    name: notebook

role:
  settings:
    - pattern: /web/notebook
      methods:
        - GET
      requiredRoles:
        - NOTEBOOK
    - pattern: /api/notebook/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - NOTEBOOK