apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  application.yaml: |
    eureka:
      client:
        enabled: false
    hystryx:
      command:
        default:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 60000
    ribbon:
      ConnectTimeout: 60000
      ReadTimeout: 60000

    event:
      processor:
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  application.yaml: |
    spring:
      datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://postgres:5432/apphub
        driverClassName: org.postgresql.Driver
      jpa:
        properties:
          hibernate:
            default_schema: public
            jdbc:
              lob:
                non_contextual_creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ribbon-config
data:
  application.yaml: |
    web-content:
      ribbon:
        listOfServers: web-content:8080
    event-gateway:
      ribbon:
        listOfServers: event-gateway:8080
    localization:
      ribbon:
        listOfServers: localization:8080
    user-data:
      ribbon:
        listOfServers: user-data:8080
    user-authentication:
      ribbon:
        listOfServers: user-authentication:8080
    user-frontend:
      ribbon:
        listOfServers: user-frontend:8080
    modules-frontend:
      ribbon:
        listOfServers: modules-frontend:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zuul-config
data:
  application.yaml: |
    zuul:
      prefix: /
      routes:
        common-resources:
          path: /res/common/**
          serviceId: web-content
          stripPrefix: false
        user-resources:
          path: /res/user/**
          serviceId: user-frontend
          stripPrefix: false
        modules-resources:
          path: /res/modules/**
          serviceId: modules-frontend
          stripPrefix: false

        localization:
          path: /localization/**
          serviceId: localization
          stripPrefix: false

        index-page:
          path: /web
          serviceId: user-frontend
          stripPrefix: false
        modules-page:
          path: /web/modules
          serviceId: modules-frontend
          stripPrefix: false

        user-data:
          path: /api/user/data/**
          serviceId: user-data
          stripPrefix: false
        user-authentication:
          path: /api/user/authentication/**
          serviceId: user-authentication
          stripPrefix: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-whitelisting-config
data:
  application.yaml: |
    endpoint:
      whitelisting:
        whiteListedEndpoints:
          resources:
            path: /res/**
            method: GET
            roles:
          localization:
            path: /localization/**
            method: GET
            roles:
          root:
            path: /
            method: GET
            roles:
          indexPage:
            path: /web
            method: GET
            roles:
          login:
            path: /api/user/authentication/login
            method: POST
            roles:
          register:
            path: /api/user/data
            method: POST
            roles: