apiVersion: v1
kind: ConfigMap
metadata:
  name: ribbon-config
data:
  application.yaml: |
    common-web-content:
      ribbon:
        listOfServers: common-web-content:8080
    localization:
      ribbon:
        listOfServers: localization:8080
    user-data:
      ribbon:
        listOfServers: user-data:8080
    user-frontend:
      ribbon:
        listOfServers: user-frontend:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  application.yaml: |
    eureka:
      client:
        enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  application.yaml: |
    spring:
      datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://postgres:5432/apphub
        driverClassName: org.postgresql.Driver
      jpa:
        properties:
          hibernate:
            default_schema: public
            jdbc:
              lob:
                non_contextual_creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zuul-config
data:
  application.yaml: |
    zuul:
      prefix: /
      routes:
        common-resources:
          path: /res/common/**
          serviceId: common-web-content
          stripPrefix: false
        user-resources:
          path: /res/user/**
          serviceId: user-frontend
          stripPrefix: false
        localization:
          path: /localization/**
          serviceId: localization
          stripPrefix: false
        index:
          path: /web
          serviceId: user-frontend
          stripPrefix: false
        user-data:
          path: /api/user/data/**
          serviceId: user-data
          stripPrefix: false