package com.github.saphyra.apphub.service.custom.elite_base.common;

public enum PerformanceReportingKey {
    SAVE_NEW_MESSAGE,
    QUERY_ARRIVED_MESSAGES,
    PROCESS_COMMODITY_MESSAGE_SAVE_STAR_SYSTEM,
    PROCESS_COMMODITY_MESSAGE_SAVE_STATION,
    PROCESS_COMMODITY_MESSAGE_SAVE_COMMODITIES,
    PROCESS_OUTFITTING_MESSAGE_SAVE_SYSTEM,
    PROCESS_OUTFITTING_MESSAGE_SAVE_STATION,
    PROCESS_OUTFITTING_MESSAGE_SAVE_LOADOUT,
    PROCESS_SHIPYARD_MESSAGE_SAVE_SYSTEM,
    PROCESS_SHIPYARD_MESSAGE_SAVE_STATION,
    PROCESS_SHIPYARD_MESSAGE_SAVE_LOADOUT,
    SAVE_COMMODITIES_QUERY,
    SAVE_COMMODITIES_DELETE_ALL,
    SAVE_COMMODITIES_SAVE_ALL,
    API_BEST_TRADE_LOCATIONS,
    SAVE_LOADOUT_QUERY_EXISTING,
    SAVE_LOADOUT_DELETE_ALL,
    SAVE_LOADOUT_SAVE_ALL,
    PROCESS_BATCH,
    ;
    public static final String PROCESS_MESSAGE = "PROCESS_MESSAGE_%s";
    public static final String PROCESS_JOURNAL_MESSAGE = "PROCESS_JOURNAL_MESSAGE_%s";
}
