friendship:
  activeTimeoutMinutes: 5

spring:
  application:
    name: skyxplore-data

liquibase:
  schema: skyxplore

setting:
  maxDataSize: 1024

game:
  deletion:
    expirationMinutes: 10
  load:
    itemsPerPage: 1000

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              skyxplore:
                data:
                  game: INFO