friendship:
  activeTimeoutMinutes: 5

spring:
  application:
    name: skyxplore-data

liquibase:
  schema: skyxplore

role:
  settings:
    - pattern: /api/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE
    - pattern: /internal/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE