friendship:
  activeTimeoutMinutes: 5

spring:
  application:
    name: skyxplore-data

liquibase:
  schema: skyxplore

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              skyxplore:
                data:
                  game: INFO