package com.github.saphyra.apphub.api.skyxplore.model.game;

public enum ProcessType {
    CONSTRUCT_CONSTRUCTION_AREA,
    DECONSTRUCT_CONSTRUCTION_AREA,
    CONSTRUCT_BUILDING_MODULE,
    DECONSTRUCT_BUILDING_MODULE,
    TERRAFORMATION,
    PRODUCTION_ORDER,
    WORK,
    STORAGE_SETTING,
    REST,
    RESOURCE_REQUEST,
    RESOURCE_DELIVERY,
    CONVOY,
    CONVOY_MOVEMENT,
    PRODUCTION_DISPATCHER,
    PRODUCTION,
}
