server:
  port: 8099

FTP_CLIENT_USERNAME: ftp_dev

ftp:
  client:
    server: localhost

storage:
  type: FTP

aws:
  dynamoDb:
    accessKeyId: dynamodbaccesskeyid
    secretKey: dynamodbsecretkey
    url: http://localhost:8000
    stored_file:
      tableName: apphub-local-stored_file