spring:
  application:
    name: user-authentication

liquibase:
  changelog:
    location: classpath:database/changelog-master.xml

accessToken:
  cookie:
    expirationDays: 365
  expirationMinutes: 10