import Endpoint from "common/js/dao/Endpoint";
import RequestMethod from "common/js/dao/RequestMethod";

export const CALENDAR_PAGE = "/web/calendar";
export const CALENDAR_LABELS_PAGE = "/web/calendar/labels";
export const CALENDAR_EXPIRED_EVENTS_PAGE = "/web/calendar/expired-events";
export const CALENDAR_SEARCH_PAGE = "/web/calendar/search";
export const CALENDAR_CREATE_EVENT_PAGE = new Endpoint(RequestMethod.GET, "/web/calendar/create-event");
export const CALENDAR_EDIT_EVENT_PAGE = new Endpoint(RequestMethod.GET, "/web/calendar/edit-event/{eventId}");
export const CALENDAR_EDIT_OCCURRENCE_PAGE = new Endpoint(RequestMethod.GET, "/web/calendar/edit-occurrence/{eventId}/{occurrenceId}");
export const CALENDAR_SHARE_PAGE = new Endpoint(RequestMethod.GET, "/web/calendar/share/{type}/{id}/{parent}");

export const CALENDAR_GET_LABELS = new Endpoint(RequestMethod.GET, "/api/calendar/labels");
export const CALENDAR_CREATE_LABEL = new Endpoint(RequestMethod.PUT, "/api/calendar/labels");
export const CALENDAR_GET_OCCURRENCES = new Endpoint(RequestMethod.GET, "/api/calendar/occurrences");
export const CALENDAR_CREATE_EVENT = new Endpoint(RequestMethod.PUT, "/api/calendar/events");
export const CALENDAR_EDIT_EVENT = new Endpoint(RequestMethod.POST, "/api/calendar/events/{eventId}");
export const CALENDAR_DELETE_LABEL = new Endpoint(RequestMethod.DELETE, "/api/calendar/labels/{labelId}");
export const CALENDAR_EDIT_LABEL = new Endpoint(RequestMethod.POST, "/api/calendar/labels/{labelId}");
export const CALENDAR_GET_EVENTS = new Endpoint(RequestMethod.GET, "/api/calendar/events");
export const CALENDAR_GET_LABELLESS_EVENTS = new Endpoint(RequestMethod.GET, "/api/calendar/events/labelless");
export const CALENDAR_GET_LABEL = new Endpoint(RequestMethod.GET, "/api/calendar/labels/{labelId}");
export const CALENDAR_GET_EVENT = new Endpoint(RequestMethod.GET, "/api/calendar/events/{eventId}");
export const CALENDAR_GET_OCCURRENCES_OF_EVENT = new Endpoint(RequestMethod.GET, "/api/calendar/events/{eventId}/occurrences");
export const CALENDAR_GET_OCCURRENCE = new Endpoint(RequestMethod.GET, "/api/calendar/{eventId}/occurrences/{occurrenceId}");
export const CALENDAR_EDIT_OCCURRENCE_STATUS = new Endpoint(RequestMethod.POST, "/api/calendar/{eventId}/occurrences/{occurrenceId}/status");
export const CALENDAR_OCCURRENCE_REMINDED = new Endpoint(RequestMethod.POST, "/api/calendar/{eventId}/occurrences/{occurrenceId}/reminded");
export const CALENDAR_DELETE_EVENT = new Endpoint(RequestMethod.DELETE, "/api/calendar/events/{eventId}");
export const CALENDAR_DELETE_OCCURRENCE = new Endpoint(RequestMethod.DELETE, "/api/calendar/{eventId}/occurrences/{occurrenceId}");
export const CALENDAR_EDIT_OCCURRENCE = new Endpoint(RequestMethod.POST, "/api/calendar/{eventId}/occurrences/{occurrenceId}");
export const CALENDAR_GET_LABELS_OF_EVENT = new Endpoint(RequestMethod.GET, "/api/calendar/events/{eventId}/labels");
export const CALENDAR_CREATE_OCCURRENCE = new Endpoint(RequestMethod.PUT, "/api/calendar/occurrences/{eventId}");
export const CALENDAR_GET_EXPIRED_EVENTS = new Endpoint(RequestMethod.GET, "/api/calendar/events/expired");
export const CALENDAR_HIDE_EXPIRED_EVENT = new Endpoint(RequestMethod.POST, "/api/calendar/events/{eventId}/hide");
export const CALENDAR_EXTEND_EXPIRED_EVENT = new Endpoint(RequestMethod.POST, "/api/calendar/events/{eventId}/extend");
export const CALENDAR_MERGE_EVENTS = new Endpoint(RequestMethod.POST, "/api/calendar/events/{eventId}/merge");
export const CALENDAR_ARCHIVE_EVENT = new Endpoint(RequestMethod.POST, "/api/calendar/events/{eventId}/archive");
export const CALENDAR_SEARCH_EVENTS = new Endpoint(RequestMethod.POST, "/api/calendar/events/search");
export const CALENDAR_GET_SHARED_OBJECT = new Endpoint(RequestMethod.GET, "/api/calendar/shared/{type}/{id}");
export const CALENDAR_GET_GRANTS = new Endpoint(RequestMethod.GET, "/api/calendar/shared/{type}/grants");
export const CALENDAR_SHARE_OBJECT = new Endpoint(RequestMethod.PUT, "/api/calendar/shared");
export const CALENDAR_SHARE_EDIT_GRANTS = new Endpoint(RequestMethod.POST, "/api/calendar/shared/{type}/{id}/grants/{sharedWith}");
export const CALENDAR_UNSHARE_OBJECT = new Endpoint(RequestMethod.DELETE, "/api/calendar/shared/{type}/{id}/grants/{sharedWith}");