const KILOBYTES = 1024;
const MEGABYTES = KILOBYTES * 1024;
const GIGABYTES = MEGABYTES * 1024;

const Constants = {
    STORAGE_KEY_TEST_MODE: "testMode",
    STORAGE_KEY_LOCALE: "apphubLocale",

    //REQUEST
    COOKIE_LOCALE: "language",
    DEFAULT_LOCALE: "en",
    HEADER_BROWSER_LANGUAGE: "BrowserLanguage",

    //VALIDATION
    MIN_USERNAME_LENGTH: 3,
    MAX_USERNAME_LENGTH: 30,
    MIN_PASSWORD_LENGTH: 6,
    MAX_PASSWORD_LENGTH: 30,
    MIN_CHARACTER_NAME_LENGTH: 3,
    MAX_CHARACTER_NAME_LENGTH: 30,
    MIN_GAME_NAME_LENGTH: 3,
    MAX_GAME_NAME_LENGTH: 30,
    FILE_SIZE_LIMIT: 209_715_200, //200 MB
    MAX_PIN_GROUP_NAME_LENGTH: 30,
    SKYXPLORE_MAX_CHAT_MESSAGE_SIZE: 1024,
    MIN_USER_SEARCH_LENGTH: 3,


    //File size
    KILOBYTES: KILOBYTES,
    MEGABYTES: MEGABYTES,
    GIGABYTES: GIGABYTES,

    //Memory monitoring
    PIXEL_PER_REPORT: 3,
    GRAPH_PADDING: 5,
    GRAPH_HEIGHT: 200,

    SETTINGS_KEY_COLLAPSED_MODULES: "collapsed-modules",

    //Characters / icons
    ICON_SHARED: " 👥\uFE0E",
}

export default Constants;