spring:
  application:
    name: skyxplore-game

abandonedGameExpirationSeconds: 30
skyXploreDataHost: skyxplore-data:8080

game:
  tickTimeMillis: 100
  pauseGameAfterDisconnectionSeconds: 5
  messageDelay:
    planetSurface: 100
    planetQueue: 100
    planetStorage: 1000
    planetPopulation: 5000
    planetBuilding: 1000
    population: 1000
  deconstruction:
    requiredWorkPoints: 20000
  itemSaverMaxChunkSize: 500
  creationQueueSize: 100
  solarSystem:
    solarSystemDistance:
      min: 100
      max: 500
    padding: 50
    planetOrbitRadius:
      min: 100
      max: 300
  planet:
    orbitSpeed:
      min: 0.1
      max: 2
    defaultRawFoodAmount: 100
  surface:
    spawnDetails:
      - surfaceName: COAL_FIELD
        spawnRate: 1
        optional: true
      - surfaceName: DESERT
        spawnRate: 3
      - surfaceName: FOREST
        spawnRate: 2
      - surfaceName: LAKE
        spawnRate: 2
      - surfaceName: MOUNTAIN
        spawnRate: 2
        optional: false
      - surfaceName: OIL_FIELD
        spawnRate: 1
      - surfaceName: ORE_FIELD
        spawnRate: 1
      - surfaceName: VOLCANO
        spawnRate: 1
        optional: true
      - surfaceName: FIELD
        spawnRate: 2
  citizen:
    workPointsPerTick: 100
    maxWorkPointsBatch: 1000
    morale:
      workEfficiencyDropUnder: 5000
      minEfficiency: 0.25
      moralePerWorkPoints: 1
      regenPerTick: 50
      minRestTicks: 10
      restingMoraleLimit: 9000 #Citizens can go resting automatically below this value
      exhaustedMorale: 1000
      exhaustedRestTicks: 100
    skill:
      experiencePerLevel: 1000
      skillLevelMultiplier: 0.1
    maxStatValues:
      # Don't forget adding new item to StatConverter's mapper
      MORALE: 10000
      SATIETY: 10000
    satiety:
      satietyDecreasedPerTick: 5
    hitPoints:
      perLevel: 1000
      base: 9000

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              skyxplore:
                game:
                  tick: INFO