spring:
  application:
    name: skyxplore-game

abandonedGameExpirationSeconds: 300

game:
  deconstruction:
    requiredWorkPoints: 1000
    parallelWorkers: 1
  eventQueueSize: 1000
  itemSaverMaxChunkSize: 500
  creationQueueSize: 100
  solarSystem:
    solarSystemDistance:
      min: 100
      max: 500
    padding: 50
    planetOrbitRadius:
      min: 100
      max: 300
  planet:
    orbitSpeed:
      min: 0.1
      max: 2
    defaultRawFoodAmount: 100
  surface:
    spawnDetails:
      - surfaceName: COAL_FIELD
        spawnRate: 1
        optional: true
      - surfaceName: DESERT
        spawnRate: 3
      - surfaceName: FOREST
        spawnRate: 2
      - surfaceName: LAKE
        spawnRate: 1
      - surfaceName: MOUNTAIN
        spawnRate: 2
        optional: false
      - surfaceName: OIL_FIELD
        spawnRate: 1
      - surfaceName: ORE_FIELD
        spawnRate: 1
      - surfaceName: VOLCANO
        spawnRate: 2
        optional: true
  citizen:
    workPointsPerSeconds: 100
    maxWorkPointsBatch: 1000
    morale:
      max: 1600
      workEfficiencyDropUnder: 800
      minEfficiency: 0.25
      moralePerWorkPoints: 1
      regenPerSecond: 10
      minRestSeconds: 15
      maxRestSeconds: 30
    skill:
      experiencePerLevel: 1000
      skillLevelMultiplier: 0.1
    satiety:
      max: 10000
      satietyDecreasedPerSecond: 50
    hitPoints:
      perLevel: 1000
      base: 9000

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              skyxplore:
                game:
                  tick: INFO