spring:
  application:
    name: skyxplore-game

game:
  creation:
    universe:
      baseSize: 500
      memberMultiplier: 1
      minMultiplier: 0.75
      maxMultiplier: 1.25
      settingMultiplier:
        SMALLEST: 0.5
        SMALL: 1
        MEDIUM: 1.5
        LARGE: 2
    solarSystem:
      minSolarSystemDistance: 100
      minPlanetDistance: 100
      radius:
        SMALL:
          min: 250
          max: 500
        MEDIUM:
          min: 500
          max: 750
        LARGE:
          min: 750
          max: 1000
        RANDOM:
          min: 500
          max: 3000
      sizeMultiplier:
        SMALL: 0.02
        MEDIUM: 0.04
        COMMON: 0.06
    systemConnection:
      maxDistanceRate: 0.3
      maxNumberOfConnections: 3
    planet:
      systemSize:
        SMALL:
          min: 1
          max: 3
        MEDIUM:
          min: 2
          max: 6
        LARGE:
          min: 3
          max: 9
        RANDOM:
          min: 1
          max: 9
      planetSize:
        SMALL:
          min: 5
          max: 10
        MEDIUM:
          min: 10
          max: 20
        LARGE:
          min: 15
          max: 30
        RANDOM:
          min: 5
          max: 30
    surface:
      spawnDetails:
        - surfaceName: COAL_MINE
          spawnRate: 1
          optional: true
        - surfaceName: DESERT
          spawnRate: 3
        - surfaceName: FOREST
          spawnRate: 2
        - surfaceName: LAKE
          spawnRate: 1
        - surfaceName: MOUNTAIN
          spawnRate: 2
          optional: false
        - surfaceName: OIL_FIELD
          spawnRate: 1
        - surfaceName: ORE_MINE
          spawnRate: 1
        - surfaceName: VOLCANO
          spawnRate: 2
          optional: true
    player:
      spawnChance:
        NONE: 0
        RARE: 10
        COMMON: 30
        EVERYWHERE: 100

role:
  settings:
    - pattern: /api/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE