apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  labels:
    app: admin-panel
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: admin-panel
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: admin-panel
    spec:
      containers:
      - name: admin-panel
        image: saphyra/apphub-service-admin_panel:release
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server,production
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  labels:
    app: admin-panel
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: admin-panel