apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyxplore-data
  labels:
    app: skyxplore-data
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: skyxplore-data
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: skyxplore-data
    spec:
      containers:
      - name: skyxplore-data
        image: saphyra/apphub-service-skyxplore-data:release
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server,production
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        startupProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3600
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: skyxplore-data
  labels:
    app: skyxplore-data
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: skyxplore-data