const SegmentType = {
    KEYWORD: "KEYWORD",
    TABLE_LOCATION: "TABLE_LOCATION",
    TABLE_NAME: "TABLE_NAME",
    SCHEMA_NAME: "SCHEMA_NAME",
    SIGN: "SIGN",
    COLUMN_VALUE_PAIRS: "COLUMN_VALUE_PAIRS",
    COLUMN_VALUE_PAIR: "COLUMN_VALUE_PAIR",
    COLUMN_NAME: "COLUMN_NAME",
    COLUMN_VALUE: "COLUMN_VALUE",
};

export default SegmentType;