server:
  port: 8087

elite-base:
  messageHandler:
    enabled: true
  messageExpiration: P30D
  messageProcessorBatchSize: 500
  executor:
    threadCount: 10
  messageProcessorRetryDelay: PT2M
  messageProcessorMaxRetryCount: 10