const QueueItemType = {
    CONSTRUCTION: "CONSTRUCTION",
    TERRAFORMATION: "TERRAFORMATION",
    DECONSTRUCTION: "DECONSTRUCTION",
    CONSTRUCT_CONSTRUCTION_AREA: "CONSTRUCT_CONSTRUCTION_AREA",
    DECONSTRUCT_CONSTRUCTION_AREA: "DECONSTRUCT_CONSTRUCTION_AREA",
}

export default QueueItemType;