const QueueItemType = {
    TERRAFORMATION: "TERRAFORMATION",
    CONSTRUCT_CONSTRUCTION_AREA: "CONSTRUCT_CONSTRUCTION_AREA",
    DECONSTRUCT_CONSTRUCTION_AREA: "DECONSTRUCT_CONSTRUCTION_AREA",
    DECONSTRUCT_BUILDING_MODULE: "DECONSTRUCT_BUILDING_MODULE",
    CONSTRUCT_BUILDING_MODULE: "CONSTRUCT_BUILDING_MODULE",
}

export default QueueItemType;