aws:
  dynamoDb:
    accessKeyId: dynamodbaccesskeyid
    secretKey: dynamodbsecretkey
    url: http://dynamodb:8000
    calendar:
      tableName: apphub-minikube-calendar
    alm:
      tableName: apphub-calendar-minikube-alm