server:
  port: 8097

aws:
  dynamoDb:
    accessKeyId: dynamodbaccesskeyid
    secretKey: dynamodbsecretkey
    url: http://localhost:8000
    calendar:
      tableName: apphub-local-calendar
    alm:
      tableName: apphub-calendar-local-alm

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              calendar: debug
