aws:
  dynamoDb:
    accessKeyId: ${DYNAMO_DB_ACCESS_KEY_ID}
    secretKey: ${DYNAMO_DB_SECRET_KEY}
    url: ~
    calendar:
      tableName: apphub-preprod-calendar
    alm:
      tableName: apphub-calendar-preprod-alm