package com.github.saphyra.apphub.lib.common_util;

public enum ErrorCode {
    BAD_CREDENTIALS,
    BAD_PASSWORD,
    CATEGORY_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_PARAM,
    INVALID_TYPE,
    LIST_ITEM_NOT_FOUND, //TODO localization
    LOCALE_NOT_FOUND,
    MISSING_ROLE,
    NO_SESSION_AVAILABLE,
    PASSWORD_TOO_LONG,
    PASSWORD_TOO_SHORT,
    ROLE_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    UNKNOWN_ERROR,
    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    USERNAME_TOO_LONG,
    USERNAME_TOO_SHORT
}
