const NotificationKey = {
    NO_VALID_SESSION: "NO_VALID_SESSION",
    REGISTRATION_SUCCESSFUL: "REGISTRATION_SUCCESSFUL",
    SUCCEESSFUL_LOGOUT: "SUCCEESSFUL_LOGOUT",
    EMPTY_CREDENTIALS: "EMPTY_CREDENTIALS",
}

export default NotificationKey;