spring:
  application:
    name: skyxplore-facade

zuul:
  prefix: /
  routes:
    #SkyXplore data
    create-or-update-character:
      path: /api/skyxplore/character
      serviceId: skyxplore-data
      stripPrefix: false
    get-character:
      path: /api/skyxplore/character
      serviceId: skyxplore-data
      stripPrefix: false
    get-friend-candidates:
      path: /api/skyxplore/friend/candidate
      serviceId: skyxplore-data
      stripPrefix: false
    create-friend-request:
      path: /api/skyxplore/friend/request
      serviceId: skyxplore-data
      stripPrefix: false
    get-friends:
      path: /api/skyxplore/friend
      serviceId: skyxplore-data
      stripPrefix: false
    remove-friend:
      path: /api/skyxplore/friend/*
      serviceId: skyxplore-data
      stripPrefix: false
    get-sent-friend-requests:
      path: /api/skyxplore/friend/request/sent
      serviceId: skyxplore-data
      stripPrefix: false
    accept-cancel-friend-request:
      path: /api/skyxplore/friend/request/*
      serviceId: skyxplore-data
      stripPrefix: false
    get-item:
      path: /api/skyxplore/data/*
      serviceId: skyxplore-data
      stripPrefix: false

    #SkyXplore lobby
    create-lobby:
      path: /api/skyxplore/lobby
      serviceId: skyxplore-lobby
      stripPrefix: false
    exit-from-lobby:
      path: /api/skyxplore/lobby
      serviceId: skyxplore-lobby
      stripPrefix: false
    invite-to-lobby:
      path: /api/skyxplore/lobby/invite/*
      serviceId: skyxplore-lobby
      stripPrefix: false
    accept-invitation:
      path: /api/skyxplore/lobby/join/*
      serviceId: skyxplore-lobby
      stripPrefix: false
    get-lobby-members:
      path: /api/skyxplore/lobby/members
      serviceId: skyxplore-lobby
      stripPrefix: false
    get-lobby-settings:
      path: /api/skyxplore/lobby/settings
      serviceId: skyxplore-lobby
      stripPrefix: false
    start-game:
      path: /api/skyxplore/lobby/start
      serviceId: skyxplore-lobby
      stripPrefix: false

    #SkyXplore game
    get-map:
      path: /api/skyxplore/game/universe
      serviceId: skyxplore-game
      stripPrefix: false
    get-players:
      path: /api/skyxplore/game/player
      serviceId: skyxplore-game
      stripPrefix: false
    create-chat-room:
      path: /api/skyxplore/game/chat/room
      serviceId: skyxplore-game
      stripPrefix: false
    leave-chat-room:
      path: /api/skyxplore/game/chat/room/*
      serviceId: skyxplore-game
      stripPrefix: false
    get-solar-system:
      path: /api/skyxplore/game/solar-system/*
      serviceId: skyxplore-game
      stripPrefix: false
    get-surface:
      path: /api/skyxplore/game/planet/*/surface
      serviceId: skyxplore-game
      stripPrefix: false
    get-planet-storage:
      path: /api/skyxplore/game/planet/*/storage
      serviceId: skyxplore-game
      stripPrefix: false
    get-planet-population-overview:
      path: /api/skyxplore/game/planet/*/population
      serviceId: skyxplore-game
      stripPrefix: false
    get-planet-building-overview:
      path: /api/skyxplore/game/planet/*/building
      serviceId: skyxplore-game
      stripPrefix: false
    get-planet-priorities:
      path: /api/skyxplore/game/planet/*/priority
      serviceId: skyxplore-game
      stripPrefix: false
    get-storage-settings:
      path: /api/skyxplore/game/planet/*/storage-settings
      serviceId: skyxplore-game
      stripPrefix: false
    create-storage-setting:
      path: /api/skyxplore/game/planet/*/storage-settings
      serviceId: skyxplore-game
      stripPrefix: false
    delete-storage-settings:
      path: /api/skyxplore/game/planet/*/storage-settings/*
      serviceId: skyxplore-game
      stripPrefix: false
    edit-storage-settings:
      path: /api/skyxplore/game/planet/*/storage-settings/*
      serviceId: skyxplore-game
      stripPrefix: false

role:
  settings:
    - pattern: /web/skyxplore/**
      methods:
        - GET
      requiredRoles:
        - SKYXPLORE
    - pattern: /api/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE
    - pattern: /internal/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE