spring:
  application:
    name: skyxplore-facade

zuul:
  prefix: /
  routes:
    get-friend-candidates:
      path: /api/skyxplore/friend/candidate
      serviceId: skyxplore-data
      stripPrefix: false
    create-friend-request:
      path: /api/skyxplore/friend/request
      serviceId: skyxplore-data
      stripPrefix: false
    get-friends:
      path: /api/skyxplore/friend
      serviceId: skyxplore-data
      stripPrefix: false
    remove-friend:
      path: /api/skyxplore/friend/*
      serviceId: skyxplore-data
      stripPrefix: false
    get-sent-friend-requests:
      path: /api/skyxplore/friend/request/sent
      serviceId: skyxplore-data
      stripPrefix: false
    accept-cancel-friend-request:
      path: /api/skyxplore/friend/request/*
      serviceId: skyxplore-data
      stripPrefix: false
    exit-from-lobby:
      path: /api/skyxplore/lobby
      serviceId: skyxplore-lobby
      stripPrefix: false
    invite-to-lobby:
      path: /api/skyxplore/lobby/invite/*
      serviceId: skyxplore-lobby
      stripPrefix: false

role:
  settings:
    - pattern: /web/skyxplore/**
      methods:
        - GET
      requiredRoles:
        - SKYXPLORE
    - pattern: /api/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE
    - pattern: /internal/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE