server:
  port: 8090

aws:
  dynamoDb:
    accessKeyId: dynamodbaccesskeyid
    secretKey: dynamodbsecretkey
    url: http://localhost:8000
    listItem:
      tableName: apphub-local-list_item
    pinGroup:
      tableName: apphub-local-notebook-pin_group