aws:
  dynamoDb:
    accessKeyId: ${DYNAMO_DB_ACCESS_KEY_ID}
    secretKey: ${DYNAMO_DB_SECRET_KEY}
    url: ~
    listItem:
      tableName: apphub-preprod-list_item
    pinGroup:
      tableName: apphub-preprod-notebook-pin_group