spring:
  application:
    name: event-gateway
liquibase:
  schema: event_gateway

eventProcessor:
  cleanup:
    expirationSeconds: 300
    interval: 60000
  backgroundEventSendingEnabled: true

logging:
  level:
    com:
      github:
        saphyra:
          apphub:
            service:
              platform:
                event_gateway: INFO