spring:
  appliction:
    name: event-gateway

liquibase:
  changelog:
    location: classpath:database/changelog-master.xml

eventProcessor:
  cleanup:
    expirationSeconds: 300
    interval: 60000
  backgroundEventSendingEnabled: true