apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: notebook
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: notebook
    spec:
      containers:
        - name: notebook
          image: saphyra/apphub-service-notebook:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 15
          resources:
            limits:
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: notebook