apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
  labels:
    app: utils
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: utils
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: utils
    spec:
      containers:
      - name: utils
        image: saphyra/apphub-service-utils:latest
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 15
        resources:
          limits:
            memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: utils
  labels:
    app: utils
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: utils