apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gateway
  labels:
    app: event-gateway
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: event-gateway
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: event-gateway
    spec:
      containers:
        - name: event-gateway
          image: saphyra/apphub-service-platform-event_gateway:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: event-gateway
  labels:
    app: event-gateway
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: event-gateway