apiVersion: apps/v1
kind: Deployment
metadata:
  name: modules-frontend
  labels:
    app: modules-frontend
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: modules-frontend
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: modules-frontend
    spec:
      containers:
        - name: modules-frontend
          image: saphyra/apphub-service-modules-frontend:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: modules-frontend
  labels:
    app: modules-frontend
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: modules-frontend