apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduler
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: scheduler
    spec:
      containers:
        - name: scheduler
          image: saphyra/apphub-service-platform-scheduler:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-content
  labels:
    app: web-content
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: web-content