apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication
  labels:
    app: user-authentication
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-authentication
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: user-authentication
    spec:
      containers:
        - name: user-authentication
          image: saphyra/apphub-service-user-authentication:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-authentication
  labels:
    app: user-authentication
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: user-authentication