apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication
  labels:
    app: user-authentication
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-authentication
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: user-authentication
    spec:
      containers:
        - name: user-authentication
          image: saphyra/apphub-service-user_authentication:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-authentication
  labels:
    app: user-authentication
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: user-authentication