apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data
  labels:
    app: user-data
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-data
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: user-data
    spec:
      containers:
        - name: user-data
          image: saphyra/apphub-service-user_data:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-data
  labels:
    app: user-data
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: user-data