apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
  labels:
    app: message-sender
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: message-sender
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: message-sender
    spec:
      containers:
      - name: message-sender
        image: saphyra/apphub-service-platform-message_sender:release
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: message-sender
  labels:
    app: message-sender
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: message-sender