apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduler
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: scheduler
    spec:
      containers:
      - name: scheduler
        image: saphyra/apphub-service-platform-scheduler:release
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server,production
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: scheduler