const EventName = {
    NOTEBOOK_LIST_ITEM_DELETED: "NOTEBOOK_LIST_ITEM_DELETED",
    NOTEBOOK_LIST_ITEM_ARCHIVED: "NOTEBOOK_LIST_ITEM_ARCHIVED",
    NOTEBOOK_LIST_ITEM_PINNED: "NOTEBOOK_LIST_ITEM_PINNED",
    NOTEBOOK_LIST_ITEM_CLONED: "NOTEBOOK_LIST_ITEM_CLONED",
    NOTEBOOK_LIST_ITEM_MODIFIED: "NOTEBOOK_LIST_ITEM_MODIFIED",
}

export default EventName;