spring:
  application:
    name: scheduler
  datasource:
    initialize: false

initialDelay: 30000

interval:
  user:
    authentication:
      accessTokenCleanup: 60000
    deletion: 5000
    revoke-ban: 60000
  skyxplore:
    lobby:
      lobbyCleanup: 300000
    game:
      gameCleanup: 300000 #5 minutes
      deletion: 60000 #1 minute
  platform:
    memoryStatusUpdateTrigger: 1000
    messageSender:
      pingRequest: 30000
      connectionCleanup: 600000
  storage:
    storedFileCleanup: 300000 #5 minutes
  eliteBase:
    processMessages: PT5S
    resetUnhandledMessages: P7D
    deleteExpiredMessages: P1D