spring:
  application:
    name: scheduler
  datasource:
    initialize: false

initialDelay: 1000

interval:
  user:
    deletion: 5000
    revoke-ban: 60000
  skyxplore:
    lobby:
      lobbyCleanup: 300000
    game:
      gameCleanup: 300000 #5 minutes
      deletion: 60000 #1 minute
  platform:
    webSocket:
      pingRequest: 30000
      connectionCleanup: 600000
  monitoring:
    aggregateSecondMetrics: 0 * * * * ? #Every minute
    aggregateMinuteMetrics: 0 0 * * * ? #Every hour
    deleteExpiredMetrics: 0 0 0 * * ? #Every day at midnight
    reportMemoryStatus: "* * * * * ?" #Every second
    reportInMemoryDaoStatus: "* * * * * ?" #Every second
    sendCollectedMetrics: "*/5 * * * * ?" #Every 5 seconds
  eliteBase:
    processMessages: PT5S
    resetUnhandledMessages: P7D
    deleteExpiredMessages: PT1H
    orphanedRecordCleanup: 0 0 3 * * * #Every day at 3AM