spring:
  application:
    name: scheduler
  datasource:
    initialize: false

interval:
  user:
    authentication:
      accessTokenCleanup: 60000
  skyxplore:
    lobby:
      lobbyCleanup: 300000