spring:
  application:
    name: scheduler
  datasource:
    initialize: false

initialDelay: 30000

interval:
  user:
    authentication:
      accessTokenCleanup: 60000
    deletion: 5000
  skyxplore:
    lobby:
      lobbyCleanup: 300000
    game:
      gameCleanup: 300000
  platform:
    messageSender:
      pingRequest: 30000
      connectionCleanup: 600000