apiVersion: apps/v1
kind: Deployment
metadata:
  name: modules
  labels:
    app: modules
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: modules
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: modules
    spec:
      containers:
        - name: modules
          image: saphyra/apphub-service-modules:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: modules
  labels:
    app: modules
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: modules