apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyxplore-lobby
  labels:
    app: skyxplore-lobby
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: skyxplore-lobby
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: skyxplore-lobby
    spec:
      containers:
        - name: skyxplore-lobby
          image: saphyra/apphub-service-skyxplore-lobby:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 4
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: skyxplore-lobby
  labels:
    app: skyxplore-lobby
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: skyxplore-lobby