apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption
  labels:
    app: encryption
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: encryption
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: encryption
    spec:
      containers:
      - name: encryption
        image: saphyra/apphub-service-platform-encryption:latest
        env:
          - name: SPRING_ACTIVE_PROFILE
            value: server
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        startupProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3600
        livenessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /platform/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        resources:
          limits:
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: encryption
  labels:
    app: encryption
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: encryption