package com.github.saphyra.apphub.ci.menu;

public enum Menu {
    LOCAL_RUN_EDIT_CONFIGURATION_ENABLE_SERVICE_MENU,
    EDIT_THREAD_COUNT_MENU,
    LOCAL_RUN_EDIT_CONFIGURATION_MENU,
    LOCAL_RUN_MODE_SELECTOR_MENU,
    LOCAL_RUN_MENU,
    MINIKUBE_MENU,
    PRODUCTION_MENU,
    PREPROD_MENU,
    PREPROD_EDIT_CONFIGURATION_MENU,
    SETTINGS_MENU,
    MINIKUBE_EDIT_CONFIGURATION_MENU,
    MINIKUBE_MODE_SELECTOR_MENU,
    PRODUCTION_EDIT_CONFIGURATIONS_MENU,
    CHANGE_LANGUAGE_MENU,
    MAIN_MENU,
    NONE
}
