<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>apphub-api</artifactId>
        <groupId>com.github.saphyra</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>apphub-api-feature</artifactId>
    <name>apphub-api-feature</name>
    <packaging>pom</packaging>

    <modules>
        <module>apphub-api-feature-calendar</module>
        <module>apphub-api-feature-community</module>
        <module>apphub-api-feature-elite_base</module>
        <module>apphub-api-feature-notebook</module>
        <module>apphub-api-feature-skyxplore</module>
    </modules>
</project>
