spring:
  application:
    name: modules

modules:
  modules:
    accounts:
      - name: account
        url: /web/account
        allowedByDefault: true
      - name: admin-panel
        url: /web/admin-panel
        allowedByDefault: false