spring:
  application:
    name: modules

modules:
  modules:
    accounts:
      - name: account
        url: /web/user/account
        allowedByDefault: true
      - name: admin-panel
        url: /web/admin-panel
        allowedByDefault: false
        roles:
          - ADMIN