spring:
  application:
    name: modules

liquibase:
  schema: modules

modules:
  modules:
    accounts:
      - name: account
        url: /web/user/account
        allowedByDefault: true
        mobileAllowed: true
      - name: admin-panel
        url: /web/admin-panel
        allowedByDefault: false
        roles:
          - ADMIN
    office:
      - name: notebook
        url: /web/notebook
        allowedByDefault: false
        mobileAllowed: true
        roles:
          - NOTEBOOK
      - name: json-formatter
        url: /web/utils/json-formatter
        allowedByDefault: true
        mobileAllowed: true
      - name: mobile-messages
        url: /web/utils/mobile-messages
        allowedByDefault: false
        mobileAllowed: true
        roles:
          - VERIMI_DEVELOPER