export const MIN_PLAYERS_PER_SOLAR_SYSTEM = 1;
export const MAX_PLAYERS_PER_SOLAR_SYSTEM = 5;
export const ADDITIONAL_SOLAR_SYSTEMS_MIN = 0;
export const ADDITIONAL_SOLAR_SYSTEMS_MAX = 30;
export const PLANETS_PER_SOLAR_SYSTEM_MIN = 0;
export const PLANETS_PER_SOLAR_SYSTEM_MAX = 10;
export const PLANET_SIZE_MIN = 10;
export const PLANET_SIZE_MAX = 20;

export const SKYXPLORE_LOBBY_TYPE_NEW = "NEW_GAME";
export const SKYXPLORE_LOBBY_TYPE_LOAD = "LOAD_GAME";