apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-content
  labels:
    app: web-content
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-content
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: web-content
    spec:
      containers:
        - name: web-content
          image: saphyra/apphub-service-platform-web_content:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /platform/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 4
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-content
  labels:
    app: web-content
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: web-content