spring:
  application:
    name: elite-base
  datasource:
    hikari:
      maximumPoolSize: 20

liquibase:
  schema: elite_base

elite-base:
  messageExpiration: P30D
  processedMessageExpiration: P3D
  messageProcessorBatchSize: 100
  messageProcessorSublistSize: 10
  executor:
    threadCount: 4
  retryDelay: PT2H
  maxRetryCount: 50