spring:
  application:
    name: elite-base
  datasource:
    hikari:
      maximumPoolSize: 20

liquibase:
  schema: elite_base

elite-base:
  messageExpiration: P30D
  messageProcessorBatchSize: 100
  messageProcessorSublistSize: 25
  executor:
    threadCount: 4