package com.github.saphyra.apphub.service.custom.elite_base.dao;

public enum Orphanage {
    STAR_SYSTEM_POWER_MAPPING,
    STAR_SYSTEM_DATA,
    MINOR_FACTION,
    STAR_SYSTEM_MINOR_FACTION_MAPPING,
    BODY,
    STATION_ECONOMY,
    STATION,
    LAST_UPDATE,
    MATERIAL_TRADER_OVERRIDE,
    POWERPLAY_CONFLICT,
    MINOR_FACTION_CONFLICT,
    BODY_MATERIAL,
    LOADOUT,
    COMMODITY,
    BODY_RING,
    BODY_DATA,
    MINOR_FACTION_STATE,
    CONFLICTING_MINOR_FACTION,
    STATION_SERVICE,
}
