package com.github.saphyra.apphub.integration.common.framework;

public enum ErrorCode {
    BAD_CREDENTIALS,
    BAD_PASSWORD,
    EMAIL_ALREADY_EXISTS,
    INVALID_PARAM,
    MISSING_ROLE,
    NO_SESSION_AVAILABLE,
    PASSWORD_TOO_LONG,
    PASSWORD_TOO_SHORT,
    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    USERNAME_TOO_LONG,
    USERNAME_TOO_SHORT
}
