const EliteBasePage = {
    INDEX: "INDEX",
    SEARCH_NEAREST: "SEARCH_NEAREST",
    SEARCH_NEAREST_MATERIAL_TRADER: "SEARCH_NEAREST_MATERIAL_TRADER",
    COMMODITY_TRADING_BUY_COMMODITIES: "COMMODITY_TRADING_BUY_COMMODITIES",
    COMMODITY_TRADING_SELL_COMMODITIES: "COMMODITY_TRADING_SELL_COMMODITIES",
    MERIT_FARMING_NAKATO_KAINE_MINING: "MERIT_FARMING_NAKATO_KAINE_MINING",
}

export default EliteBasePage;