apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    type: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        serviceType: spring-app
        name: user
    spec:
      containers:
        - name: user
          image: saphyra/apphub-service-user:release
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: user