role:
  settings:
    - pattern: /api/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE
    - pattern: /internal/skyxplore/**
      methods:
        - GET
        - DELETE
        - POST
        - PUT
      requiredRoles:
        - SKYXPLORE